# Generated by Django 4.1.6 on 2023-02-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_stocks_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
