# Generated by Django 4.1.6 on 2023-02-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_user_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='balance',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
    ]
